### ISSUE TITLE
when running convert.py there's a problem

### ISSUE THREAD

**Issue by illutheplanet** [chayka/LabelMe2CocoDataset#1]
Traceback (most recent call last):
  File "convert.py", line 160, in <module>
    }, fa, indent='  ')
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 353, in _iterencode_dict
    newline_indent = '\n' + (' ' * (_indent * _current_indent_level))
TypeError: can't multiply sequence by non-int of type 'str'

Also, I'm not sure how to set arguments. Could you tell me more?

**Comment by chayka** [comment]
@illutheplanet Hi there. This script was intended to convert images labeled with labelme tool (https://github.com/wkentaro/labelme) to some format that Detectron (https://github.com/facebookresearch/Detectron) can understand. Among others detectron understands http://cocodataset.org format. The input images are stored as json files produced by labelme. Json files are stored in ./input/DATASET_NAME folder. Then DATASET_NAME is provided as main param to the convert.py script. If everything works correct you can expect output in ./output/DATASET_NAME folder. Contents of this folder should be compatible with COCODataset.
